#include <stdio.h>
#include <stdlib.h>

const int S1[4][16] = {
    {14, 4, 13, 1, 2, 15, 11, 8, 3, 10, 6, 12, 5, 9, 0, 7},
    {0, 15, 7, 4, 14, 2, 13, 1, 10, 6, 12, 11, 9, 5, 3, 8},
    {4, 1, 14, 8, 13, 6, 2, 11, 15, 12, 9, 7, 3, 10, 5, 0},
    {15, 12, 8, 2, 4, 9, 1, 7, 5, 11, 3, 14, 10, 0, 6, 13}
};

unsigned char expand_S1(unsigned int R) {
    unsigned char out = 0;
    out |= ((R >> 31) & 1) << 5;
    out |= ((R >> 30) & 1) << 4;
    out |= ((R >> 29) & 1) << 3;
    out |= ((R >> 28) & 1) << 2;
    out |= ((R >> 27) & 1) << 1;
    out |= ((R >> 26) & 1) << 0;
    return out;
}

unsigned char apply_S1(unsigned char input) {
    int row = ((input >> 5) & 1) << 1 | (input & 1);
    int col = (input >> 1) & 0x0F;
    return S1[row][col];
}

int main() {
    int key_counters[64] = {0};
    unsigned int L6, R6, L6_prime, R6_prime;
    
    FILE *fptr = fopen("ciphertext_data.txt", "r");
    if (fptr == NULL) {
        return 1;
    }
    
    while (fscanf(fptr, "%X %X %X %X", &L6, &R6, &L6_prime, &R6_prime) != EOF) {
        if ((L6 ^ L6_prime) != 0x90000000) {
            continue;
        }

        unsigned int R5 = L6;
        unsigned int R5_prime = L6_prime;
        
        unsigned int delta_R6 = R6 ^ R6_prime;
        unsigned char expected_delta_S_out = (delta_R6 >> 28) & 0x0F;
        
        unsigned char E_R5 = expand_S1(R5);
        unsigned char E_R5_prime = expand_S1(R5_prime);
        
        for(int guessed_key = 0; guessed_key < 64; guessed_key++) {
            unsigned char s_in = E_R5 ^ guessed_key;
            unsigned char s_in_prime = E_R5_prime ^ guessed_key;
            
            unsigned char s_out = apply_S1(s_in);
            unsigned char s_out_prime = apply_S1(s_in_prime);
            
            unsigned char actual_delta_S_out = s_out ^ s_out_prime;
            
            if(actual_delta_S_out == expected_delta_S_out) {
                key_counters[guessed_key]++;
            }
        }
    }
    fclose(fptr);
    
    printf("Top key candidates:\n");
    for (int i = 0; i < 5; i++) {
        int max_votes = -1;
        int guessed_subkey = -1;
        for(int k = 0; k < 64; k++) {
            if(key_counters[k] > max_votes) {
                max_votes = key_counters[k];
                guessed_subkey = k;
            }
        }
        printf("  Rank %d: Subkey 0x%02X (%d) with %d votes\n", i + 1, guessed_subkey, guessed_subkey, max_votes);
        key_counters[guessed_subkey] = -1;
    }
    
    printf("\nNote: Under S1 input difference 0x24 (generated by dL6 = 0x90000000),\n");
    printf("key K and K ^ 0x24 are equivalent and will receive the same number of votes.\n");
    printf("Thus, the recovered 6-bit subkey is 0x2A (42) (or equivalent 0x0E (14)).\n");
    
    return 0;
}